export const FETCH_STORIES = 'FETCH_STORIES';
export const FETCH_USER = 'FETCH_USER';
export const POST_STORY = 'POST_STORY';
export const UPDATE_USER = 'UPDATE_USER';
export const SELECT_STORY = 'SELECT_STORY';
export const FETCH_STORY = 'FETCH_STORY';
export const DELETE_STORY = 'DELETE_STORY';
export const FETCH_AUTHOR = 'FETCH_AUTHOR';
export const FETCH_AUTHOR_BASIC = 'FETCH_AUTHOR_BASIC';
export const UPDATE_STORY_COMMENTS = 'UPDATE_STORY_COMMENTS';
export const POST_SNIPPET = 'POST_SNIPPET';
export const FETCH_SNIPPETS = 'FETCH_SNIPPETS';
export const PAGINATE = 'PAGINATE';
export const DELETE_SNIPPET = 'DELETE_SNIPPET';
export const EDIT_STORY = 'EDIT_STORY';






