export const FETCH_STORIES = 'FETCH_STORIES';
export const FETCH_USER = 'FETCH_USER';
export const LOG_OUT = 'LOG_OUT';
export const POST_STORY = 'POST_STORY';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATING_USERNAME = 'UPDATING_USERNAME';
export const UPDATING_DESCRIPTION = 'UPDATING_DESCRIPTION';
export const SELECT_STORY = 'SELECT_STORY';
export const FETCH_STORY = 'FETCH_STORY';
export const FETCH_STORY_REQUEST = 'FETCH_STORY_REQUEST';
export const DELETE_STORY = 'DELETE_STORY';
export const FETCH_AUTHOR = 'FETCH_AUTHOR';
export const FETCH_AUTHOR_BASIC = 'FETCH_AUTHOR_BASIC';
export const UPDATE_STORY_COMMENTS = 'UPDATE_STORY_COMMENTS';
export const POST_SNIPPET = 'POST_SNIPPET';
export const FETCH_SNIPPETS = 'FETCH_SNIPPETS';
export const PAGINATE = 'PAGINATE';
export const DELETE_SNIPPET = 'DELETE_SNIPPET';
export const EDIT_STORY = 'EDIT_STORY';
export const CLEAN_UP = 'CLEAN_UP';
export const FETCH_USER_STORIES = 'FETCH_USER_STORIES';
export const ADD_ERROR = 'ADD_ERROR';
export const DELETE_USER = 'DELETE_USER';
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const DROP_NAV = 'DROP_NAV';
export const UNDROP_NAV = 'UNDROP_NAV';

export const INIT_FETCH_STORIES = 'INIT_FETCH_STORIES';
export const LOADING = 'LOADING';

export const CLEAR_STORIES = "CLEAR_STORIES";
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR_AUTHOR = 'CLEAR_AUTHOR';
export const CLEAR_STORY = 'CLEAR_STORY';
export const CLEAR_SNIPPETS = 'CLEAR_SNIPPETS';
export const CLEAR_USER_STORIES = 'CLEAR_USER_STORIES';
export const CLEAR_PAGINATION = "CLEAR_PAGINATION";










